.Dd January 22, 2022
.Dt fvdeinfo
.Os libfvde
.Sh NAME
.Nm fvdeinfo
.Nd determines information about a FileVault Drive Encrypted (FVDE) volume
.Sh SYNOPSIS
.Nm fvdeinfo
.Op Fl e Ar plist_path
.Op Fl k Ar key
.Op Fl o Ar offset
.Op Fl p Ar password
.Op Fl r Ar password
.Op Fl huvV
.Ar sources
.Sh DESCRIPTION
.Nm fvdeinfo
is a utility to determine information about a FileVault Drive Encrypted (FVDE) volume
.Pp
.Nm fvdeinfo
is part of the
.Nm libfvde
package.
.Nm libfvde
is a library to access the FileVault Drive Encryption (FVDE) format
.Pp
.Ar sources
one or more source files or devices.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl e Ar plist_path
specify the path of the EncryptedRoot.plist.wipekey file
.It Fl h
shows this help
.It Fl k Ar key
specify the volume master key formatted in base16
.It Fl o Ar offset
specify the volume offset
.It Fl p Ar password
specify the password
.It Fl r Ar password
specify the recovery password
.It Fl u
unattended mode (disables user interaction)
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# fvdeinfo -o20480 image.raw
fvdeinfo 20220116
.sp
Core Storage information:
.sp
Logical volume group:
	Identifier			: 94923b58-9f31-4988-8707-cb90c8e45a46
	Name				: TESTLVG
	Number of physical volumes	: 1
	Number of logical volumes	: 1
.sp
Physical volume: 1
	Identifier			: 3273a055-3b8b-47e8-b970-df35eecda81b
	Size				: 511 MiB (536829952 bytes)
	Encryption method		: AES-XTS
.sp
Logical volume: 1
	Identifier			: 420af122-cf73-4a30-8b0a-a593a65fbef5
	Name				: TestLV
	Size				: 160 MiB (167772160 bytes)
	Is locked
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind on the project issue tracker: https://github.com/libyal/libfvde/issues
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2011-2022, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr fvdemount 1
