.Dd January 22, 2022
.Dt fvdemount
.Os libfvde
.Sh NAME
.Nm fvdemount
.Nd mounts a FileVault Drive Encrypted (FVDE) volume
.Sh SYNOPSIS
.Nm fvdemount
.Op Fl e Ar plist_path
.Op Fl k Ar key
.Op Fl o Ar offset
.Op Fl p Ar password
.Op Fl r Ar password
.Op Fl X Ar extended_options
.Op Fl huvV
.Ar sources
.Sh DESCRIPTION
.Nm fvdemount
is a utility to mount a FileVault Drive Encrypted (FVDE) volume
.Pp
.Nm fvdemount
is part of the
.Nm libfvde
package.
.Nm libfvde
is a library to acess the FileVault Drive Encryption (FVDE) format
.Pp
.Ar sources
one or more source files or devices.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl e Ar plist_path
specify the path of the EncryptedRoot.plist.wipekey file
.It Fl h
shows this help
.It Fl k Ar key
specify the volume master key formatted in base16
.It Fl o Ar offset
specify the volume offset
.It Fl p Ar password
specify the password
.It Fl r Ar password
specify the recovery password
.It Fl u
unattended mode (disables user interaction)
.It Fl v
verbose output to stderr
.It Fl V
print version
.It Fl X Ar extended_options
extended options to pass to sub system
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# fvdemount -p Password /dev/sda1
fvdemount 20121113

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind on the project issue tracker: https://github.com/libyal/libfvde/issues
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2011-2022, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr fvdeinfo 1
