.Dd June 26, 2026
.Dt LIBFVDE 3
.Os
.Sh NAME
.Nm libfvde.h
.Nd Library to access the Core Storage (CS) format
.Sh SYNOPSIS
.In libfvde.h
.Pp
Support functions
.nf
.Ft const char *
.Fo libfvde_get_version
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_get_access_flags_read
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_get_codepage
.Fa "int *codepage"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_set_codepage
.Fa "int codepage"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_check_volume_signature
.Fa "const char *filename"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Available when compiled with wide character string support:
.nf
.Ft int
.Fo libfvde_check_volume_signature_wide
.Fa "const wchar_t *filename"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libfvde_check_volume_signature_file_io_handle
.Fa "libbfio_handle_t *file_io_handle"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Notify functions
.nf
.Ft void
.Fo libfvde_notify_set_verbose
.Fa "int verbose"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_notify_set_stream
.Fa "FILE *stream"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_notify_stream_open
.Fa "const char *filename"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_notify_stream_close
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Error functions
.nf
.Ft void
.Fo libfvde_error_free
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_error_fprint
.Fa "libfvde_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_error_sprint
.Fa "libfvde_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_error_backtrace_fprint
.Fa "libfvde_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_error_backtrace_sprint
.Fa "libfvde_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.Pp
Volume functions
.nf
.Ft int
.Fo libfvde_volume_initialize
.Fa "libfvde_volume_t **volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_free
.Fa "libfvde_volume_t **volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_signal_abort
.Fa "libfvde_volume_t *volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_open
.Fa "libfvde_volume_t *volume"
.Fa "const char *filename"
.Fa "int access_flags"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_open_physical_volume_files
.Fa "libfvde_volume_t *volume"
.Fa "char * const filenames[]"
.Fa "int number_of_filenames"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_close
.Fa "libfvde_volume_t *volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_read_encrypted_root_plist
.Fa "libfvde_volume_t *volume"
.Fa "const char *filename"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_read_encrypted_root_plist_wide
.Fa "libfvde_volume_t *volume"
.Fa "const wchar_t *filename"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_get_volume_group
.Fa "libfvde_volume_t *volume"
.Fa "libfvde_volume_group_t **volume_group"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Available when compiled with wide character string support:
.nf
.Ft int
.Fo libfvde_volume_open_wide
.Fa "libfvde_volume_t *volume"
.Fa "const wchar_t *filename"
.Fa "int access_flags"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_open_physical_volume_files_wide
.Fa "libfvde_volume_t *volume"
.Fa "wchar_t * const filenames[]"
.Fa "int number_of_filenames"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libfvde_volume_open_file_io_handle
.Fa "libfvde_volume_t *volume"
.Fa "libbfio_handle_t *file_io_handle"
.Fa "int access_flags"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_open_physical_volume_files_file_io_pool
.Fa "libfvde_volume_t *volume"
.Fa "libbfio_pool_t *file_io_pool"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_read_encrypted_root_plist_file_io_handle
.Fa "libfvde_volume_t *volume"
.Fa "libbfio_handle_t *file_io_handle"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Volume group functions
.nf
.Ft int
.Fo libfvde_volume_group_free
.Fa "libfvde_volume_group_t **volume_group"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_identifier
.Fa "libfvde_volume_group_t *volume_group"
.Fa "uint8_t *uuid_data"
.Fa "size_t uuid_data_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_utf8_name_size
.Fa "libfvde_volume_group_t *volume_group"
.Fa "size_t *utf8_string_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_utf8_name
.Fa "libfvde_volume_group_t *volume_group"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_utf16_name_size
.Fa "libfvde_volume_group_t *volume_group"
.Fa "size_t *utf16_string_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_utf16_name
.Fa "libfvde_volume_group_t *volume_group"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_number_of_physical_volumes
.Fa "libfvde_volume_group_t *volume_group"
.Fa "int *number_of_physical_volumes"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_physical_volume_by_index
.Fa "libfvde_volume_group_t *volume_group"
.Fa "int volume_index"
.Fa "libfvde_physical_volume_t **physical_volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_number_of_logical_volumes
.Fa "libfvde_volume_group_t *volume_group"
.Fa "int *number_of_logical_volumes"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_volume_group_get_logical_volume_by_index
.Fa "libfvde_volume_group_t *volume_group"
.Fa "int volume_index"
.Fa "libfvde_logical_volume_t **logical_volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Physical volume functions
.nf
.Ft int
.Fo libfvde_physical_volume_free
.Fa "libfvde_physical_volume_t **physical_volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_physical_volume_get_identifier
.Fa "libfvde_physical_volume_t *physical_volume"
.Fa "uint8_t *uuid_data"
.Fa "size_t uuid_data_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_physical_volume_get_encryption_method
.Fa "libfvde_physical_volume_t *physical_volume"
.Fa "uint32_t *encryption_method"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_physical_volume_get_size
.Fa "libfvde_physical_volume_t *physical_volume"
.Fa "size64_t *size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Logical volume functions
.nf
.Ft int
.Fo libfvde_logical_volume_free
.Fa "libfvde_logical_volume_t **logical_volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_unlock
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libfvde_logical_volume_read_buffer
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libfvde_logical_volume_read_buffer_at_offset
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "void *buffer"
.Fa "size_t buffer_size"
.Fa "off64_t offset"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft off64_t
.Fo libfvde_logical_volume_seek_offset
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "off64_t offset"
.Fa "int whence"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_get_offset
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "off64_t *offset"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_get_identifier
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "uint8_t *uuid_data"
.Fa "size_t uuid_data_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_get_utf8_name_size
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "size_t *utf8_string_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_get_utf8_name
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_get_utf16_name_size
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "size_t *utf16_string_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_get_utf16_name
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_get_size
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "size64_t *size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_is_locked
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_set_key
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "const uint8_t *volume_master_key"
.Fa "size_t volume_master_key_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_set_utf8_password
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "const uint8_t *utf8_string"
.Fa "size_t utf8_string_length"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_set_utf16_password
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "const uint16_t *utf16_string"
.Fa "size_t utf16_string_length"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_set_utf8_recovery_password
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "const uint8_t *utf8_string"
.Fa "size_t utf8_string_length"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_logical_volume_set_utf16_recovery_password
.Fa "libfvde_logical_volume_t *logical_volume"
.Fa "const uint16_t *utf16_string"
.Fa "size_t utf16_string_length"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
LVF encryption context and EncryptedRoot.plist file functions
.nf
.Ft int
.Fo libfvde_encryption_context_plist_initialize
.Fa "libfvde_encryption_context_plist_t **plist"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_encryption_context_plist_free
.Fa "libfvde_encryption_context_plist_t **plist"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_encryption_context_plist_get_data_size
.Fa "libfvde_encryption_context_plist_t *plist"
.Fa "size64_t *data_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_encryption_context_plist_copy_data
.Fa "libfvde_encryption_context_plist_t *plist"
.Fa "uint8_t *data"
.Fa "size_t data_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libfvde_encryption_context_plist_decrypt
.Fa "libfvde_encryption_context_plist_t *plist"
.Fa "const uint8_t *key"
.Fa "size_t key_bit_size"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libfvde_encryption_context_plist_read_file_io_handle
.Fa "libfvde_encryption_context_plist_t *plist"
.Fa "libbfio_handle_t *file_io_handle"
.Fa "libfvde_error_t **error"
.Fc
.fi
.Sh DESCRIPTION
The
.Fn libfvde_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or \-1 on error, dependent on the return \
type.
For the actual return values see
.In libfvde.h .
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh NOTES
libfvde can be compiled with wide character support (wchar_t).
.sp
To compile libfvde with wide character support use:
.Ar ./configure --enable-wide-character-type
 or define:
.Ar _UNICODE
 or
.Ar UNICODE
 during compilation.
.sp
.Ar LIBFVDE_WIDE_CHARACTER_TYPE
 in libfvde/features.h can be used to determine if libfvde was compiled with \
wide character support.
.Sh SEE ALSO
.In libfvde.h
.Sh AUTHORS
.An Omar Choudary <choudary.omar@gmail.com> ,
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libfvde/issues
.Sh COPYRIGHT
Copyright (C) 2011-2026, Omar Choudary <choudary.omar@gmail.com>, \
Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
