coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    project: true
    patch: true
    changes: false
  ignore:
    - "libbfio/*"
    - "libcaes/*"
    - "libcdata/*"
    - "libcerror/*"
    - "libcfile/*"
    - "libclocale/*"
    - "libcnotify/*"
    - "libcpath/*"
    - "libcsplit/*"
    - "libcthreads/*"
    - "libfcache/*"
    - "libfdata/*"
    - "libfguid/*"
    - "libfplist/*"
    - "libfvalue/*"
    - "libhmac/*"
    - "libuna/*"
    - "tests/*"
