= FileVault Drive Encryption (FVDE)
Analysis of FVDE

:numbered!:
[abstract]
== Summary
The FileVault Drive Encryption (FVDE) format is used by Apple MacOS-X to 
encrypt volumes. This specification is based on available documentation and was 
enhanced by reverse engineering of the file format.

This document is intended as a working document for the FileVault Drive 
Encryption (FVDE) format specification. Which should allow existing Open Source 
forensic tooling to be able to process this volume type.

[preface]
== Document information
[cols="1,5"]
|===
| Author(s): | Omar Choudary <choudary.omar@gmail.com> +
Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the MacOS-X FileVault Drive Encryption (FVDE) format
| Classification: | Public
| Keywords: | FileVault 2, FileVault Drive Encryption, FVDE, Core Storage, CoreStorage
|===

[preface]
== License
....
Copyright (C) 2011-2015, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the 
terms of the GNU Free Documentation License, Version 1.3 or any later version 
published by the Free Software Foundation; with no Invariant Sections, no 
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included 
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history
[cols="1,1,1,5",options="header"]
|===
| Version | Author(s) | Date | Comments
| 0.0.1 | O. Choudary | September 2011 | Initial version.
| 0.0.2 | J.B. Metz | May 2012 | Format changes and additional information. +
Added secondary encrypted metadata block.
| 0.0.3 | J.B. Metz | July 2012 +
August 2012 +
September 2012 +
November 2012 | Additional information regarding CoreStorage.
| 0.0.4 | O. Choudary | November 2012 | Textual updates.
| 0.0.5 | J.B. Metz | December 2012 | Updates for Mac OS X 10.8 (Mountain Lion)
| 0.0.6 | J.B. Metz | February 2013 | Additional findings with thanks to O. De Lampugnani, Y. Khatri and D. Parker.
| 0.0.7 | J.B. Metz | March 2013 | Additional information regarding CoreStorage.
| 0.0.8 | J.B. Metz | February 2015 | Switched to asccidoc format.
|===

:numbered:
== Overview
FileVault Drive Encryption (FVDE) is the volume encryption used by Apple 
MacOS-X as of Lion (10.7).

This document was initially written for FVDE, but the structures mentioned are 
also used by the Core Storage (CS) volume management system. CS supports both 
non-encrypted and encrypted volumes.

CS distinguishes between different types of encrypt volumes:

* EncryptedRoot.plist.wipekey protected volume; this volume can be accessed via multiple user passwords or a recovery password. The disk that contains the volume should also have a partition name "Recovery HD" that contains the EncryptedRoot.plist.wipekey file. This is also referred to as FVDE.
* Pass-phrase protected volume, this volume can be accessed via a known pass-phrase and uses XML plist-like data identified as "com.apple.corestorage.lvf.encryption.context".

Both EncryptedRoot.plist.wipekey and 
"com.apple.corestorage.lvf.encryption.context" are definined as the the 
encryption context plist in this document.

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | Little-endian +
Except for UUID/GUID values, which are stored in big-endian
| Date and time values | 
| Character strings | Unicode stored as UTF-8
|===

=== Test version
The following version of programs were used to test the information within this document:

* MacOS-X Lion (10.7)
* MacOS-X Mountain Lion (10.8)
* MacOS-X (10.9) Mavericks
* MacOS-X (10.10) Yosemite

== Keys
To encrypt storage media CoreStorage uses different kind of keys.

=== Volume master key
The Volume Master Key (VMK) is used to encrypt the data on the volume.

The VMK is 128-bit of size and is stored in multiple KEKWrappedVolumeKeyStruct 
structures in the encryption context plist.

=== Volume tweak key
The volume tweak is the second key required by AES-XTS to decrypt the data on 
the volume. The volume tweak is 128-bit of size and is determined as follows:

First the 128-bit volume master key is concatenated with the 128-bit logical 
volume family identifier (UUID) (com.apple.corestorage.lv.familyUUID) as the 
tweak key data.

Then the one-way function SHA256 is applied to the tweak key data, so that only 
the first 128 bits is retained as the volume tweak key:
....
volume tweak key = SHA256( tweak key data )
....

=== EncryptedRoot.plist.wipekey master key
The physical volume identifier (128-bit UUID) of the encrypted volume is used 
to decrypt the EncryptedRoot.plist.wipekey file. This identifier can be found 
in the CS volume header.

=== Recovery key
FileVault provides for a recovery password to unlock the encrypted data. The 
recovery password is used to determine a recovery key.

Example recovery password:
....
35AJ-AC98-TI1H-N4M3-HDUQ-UQFG
....

This recovery password is used as a string, including the dashes between the 
digits. The corresponding recovery key is calculated using the PBKDF2 algorithm 
with:

* Apply the PBKDF2 algorithm using:
  * number of iterations
  * SHA256 as the pseudo-random function (PRF)
  * a salt, as stored in the corresponding PassphraseWrappedKEKStruct in the EncryptedRoot.plist.wipekey file
  * the recovery password

The PassphraseWrappedKEKStruct contains the primary key to unlock the 
KEKWrappedVolumeKeyStruct containing the volume master key.

1. The recovery key is used to retrieve a Key Encrypting Key (KEK) by decrypting a blob in the PassphraseWrappedKEKStruct.
2. This KEK is then used to recover the Volume Master Key (VMK) from the KEKWrappedVolumeKeyStruct.

The number of iterations is stored in the PassphraseWrappedKEKStruct but seems 
to be consistently 41000 for EncryptedRoot.plist.wipekey protected volumes on 
Mac OS X Lion.

=== User key
For every user on an Mac OS X system with FVDE, FileVault provides for a user 
password to unlock the encrypted data. The user password is used to determine a 
user key.

[yellow-background]*For now it is assumed that the user password contains ASCII characters only.*
[yellow-background]*TODO determine if other characters are allowed and how they are encoded during the password derivation.*

The corresponding user key is calculated and used in the same manner as the 
recovery key to obtain the volume master key. However each user has its own 
associated PassphraseWrappedKEKStruct.

== Encryption methods
FileVault Disk Encryption uses the AES-XTS encryption method to encrypt both 
the volume metadata and sector data. FileVault uses different methods to 
encrypt a multi-user system volume and single-user removable media volume.

=== AES-XTS
The AES-XTS encryption method uses:

* a primary key (key 1) to encrypt/decrypt the data (the whitened 
plaintext/ciphertext).
* a secondary key (key 2) to encrypt/ decrypt the tweak value, also referred to 
as the tweak key. The encrypted tweak value is used to whiten the 
plaintext/ciphertext.
* a tweak value

The cipher block size is 128 bytes.

See `[IEEE 1619-2007]` for more information.

The EncryptedRoot.plist.wipekey is encrypted using the "volume key data" of the 
FileVault encrypted volume as primary key, and a sequence of 0-byte values as 
both the tweak key and the tweak value. The unit size is the entire file.

The volume metadata is encrypted using the volume "key data" as primary key, 
the "physical volume identifier" of the volume as tweak key and a sequence of 
0-byte values as the tweak value. The unit size is 8192 bytes. Both the "volume 
key data" and "physical volume identifier" can be found in the volume header of 
the corresponding volume.

The volume sector data is encrypted using the "volume master key" as primary 
key, the "volume tweak key" as tweak key and the sector number as tweak value. 
The tweak value is the corresponding sector number represented as a 128-bit 
little-endian value. The unit size is the sector size, commonly 512 bytes.

=== Encrypted system volume
In an encrypted system volume the EncryptedRoot.plist.wipekey contains the 
volume master key. A pass-phrase or recovery password is used to unlock an 
intermediate key which provides access to the volume master key.

=== Encrypted removable media volume
FileVault2 support multiple ways to encrypt a removable media volume, several 
of the know methods are:

* with an encryption context
* without an encryption context
* decrypted

==== With an encryption context
In an encrypted removable media volume with an encryption context the XML 
plist-like data identified as "com.apple.corestorage.lvf.encryption.context" 
stored in the encrypted metadata contains the volume master key. A pass-phrase 
is used to unlock an intermediate key which provides access to the volume 
master key.

==== Without an encryption context
[yellow-background]*TODO*

==== Decrypted volume
diskutil cs decryptVolume will decrypt the volume but the data on-disk is still 
encrypted with the [yellow-background]*TODO*.

== Volume header
The volume header is 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Checksum +
Contains a CRC-32 of bytes 8 to 512
| 4 | 4 | 0xffffffff | Initial value of the CRC-32
| 8 | 2 | 1 | Version
| 10 | 2 | 0x0010 | Block type
| 12 | 4 | | [yellow-background]*(Block) serial number*
| 16 | 8 | [yellow-background]*0x00000001* | [yellow-background]*Unknown*
| 24 | 8 | | [yellow-background]*Unknown (Empty values)*
| 32 | 8 | | [yellow-background]*Unknown (Empty values)*
| 40 | 8 | | [yellow-background]*Unknown (Empty values)*
| 48 | 4 | | Bytes per sector +
[yellow-background]*(header block size?)*
| 52 | 4 | | [yellow-background]*Unknown (Empty values)*
| 56 | 8 | | [yellow-background]*Unknown (Empty values)*
| 64 | 8 | | Physical volume size (in bytes)
| 72 | 16 | | [yellow-background]*Unknown* +
[yellow-background]*(Assumed to be resize flags? Could this be the resize volume size and/or resize stack size)*
| 88 | 2 | "CS" | CoreStorage signature
| 90 | 4 | | Checksum algorithm +
See section: <<checksum_algorithms,Checksum algorithms>>
| 94 | 2 | 4 | [yellow-background]*Number of metadata blocks?* +
[yellow-background]*Maximum of 8?*
| 96 | 4 | | Block size (in bytes)
| 100 | 4 | | Metadata size (in bytes)
| 104 | 8 | | First metadata block number +
The block number is relative from the start of the volume +
[yellow-background]*(why is this referred to as disklabel block?)*
| 112 | 8 | | Second metadata block number +
The block number is relative from the start of the volume
| 120 | 8 | | Third metadata block number +
The block number is relative from the start of the volume
| 128 | 8 | | Fourth metadata block number +
The block number is relative from the start of the volume
| 136 | 4 x 8 = 32 | | [yellow-background]*Reserved for medadata block numbers?*
| 168 | 4 | 16 | Key data size
| 172 | 4 | 2 | Encryption method +
2 => AES-XTS
| 176 | 16 | | Key data
| 192 | 112 | | [yellow-background]*Unknown (empty values)* +
[yellow-background]*Reserved for key data?*
| 304 | 16 | | Physical volume identifier +
Contains an UUID in big-endian +
Used as the AES-XTS tweak key
| 304 | 16 | | Logical volume group identifier (com.apple.corestorage.lv.groupUUID) +
Contains an UUID in big-endian
| 336 | 176 | | [yellow-background]*Unknown (empty values)* +
[yellow-background]*Unused*
|===

A copy of the volume header is stored at the end of the volume, this copy is 
checked when the volume header at the start of the volume is corrupt.

=== [[checksum_algorithms]]Checksum algorithms

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 1 | CRC-32C | CRC-32 using the Castagnoli polynomial of 0x1edc6f41, also known as CRC-32C. +
The CRC-32 calculation does not use the XOR with 0xffffffff before and after the calculation, which is also referred to as weak CRC-32 calculation.
|===

== Metadata (section)
The metadata (section) (also referred to CS as disk label) consists of:

* a metadata block type 0x0011
  * a metadata block header
  * metadata block data
* volume groups descriptor

[yellow-background]*TODO, value index and plist ?*

The size of the metadata block is defined in the volume header, which commonly is 4 MiB.

=== Metadata block header
The metadata block header is 72 bytes of size and consists of:

**TODO: migrate remaining documenation.**

== Encrypted metadata (section)

**TODO: migrate remaining documenation.**

== The encryption context plist
The encryption context plist either the EncryptedRoot.plist.wipekey stored on 
the "Recovery HD" partition of the system disk that also contains the FileVault 
encrypted volume, or the XML plist-like data identified as 
"com.apple.corestorage.lvf.encryption.context" stored in the encrypted 
metadata, contains the encrypted VMKs necessary to unlock the encrypted volume.

The EncryptedRoot.plist.wipekey is encrypted and can be decrypted using 128-bit 
AES-XTS:

* as primary key the physical volume identifier of the FileVault encrypted volume (128-bit)
* as secondary key 0 (128-bit)
* a tweak value of 0
* a cypher block size as the entire file

The unencrypted encryption context plist contains:

* A PassphraseWrappedKEKStruct; one for each recovery or user passwords
* A KEKWrappedVolumeKeyStruct containing the volume key

Below an example of the contents of an unencrypted EncryptedRoot.plist.wipekey 
file.
....
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>ConversionInfo</key>
        <dict>
                <key>ConversionStatus</key>
                <string>Complete</string>
                <key>TargetContext</key>
                <integer>1</integer>
        </dict>
        <key>CryptoUsers</key>
        <array>
                <dict>
                        ...
                        <key>PassphraseWrappedKEKStruct</key>
                        <data>
                        ...
                        </data>
                        ...
                </dict>
                <dict>
                ...
                </dict>
        </array>
        <key>LastUpdateTime</key>
        <integer>1323243315</integer>
        <key>WrappedVolumeKeys</key>
        <array>
                <dict>
                        <key>BlockAlgorithm</key>
                        <string>None</string>
                        <key>KEKWrappedVolumeKeyStruct</key>
                        <data>
                        </data>
                        ...
                </dict>
                <dict>
                        <key>BlockAlgorithm</key>
                        <string>AES-XTS</string>
                        <key>KEKWrappedVolumeKeyStruct</key>
                        <data>
                        ...
                        </data>
                        ...
                </dict>
        </array>
</dict>
</plist>
....

[NOTE]
The doctype and plist definition are not present in the XML plist-like data 
identified as "com.apple.corestorage.lvf.encryption.context".

Both the PassphraseWrappedKEKStruct and KEKWrappedVolumeKeyStruct are stored as 
base64.

[yellow-background]*Is a 52 character limit (per line) enforced for the base64 encoded data?*

The purpose of the first KEKWrappedVolumeKeyStruct in the 
EncryptedRoot.plist.wipekey file is currently unknown.

=== PassphraseWrappedKEKStruct
The PassphraseWrappedKEKStruct is 284 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 3 | Value type
| 4 | 4 | 16 | Value size
| 8 | 16 | | Salt for the PBKDF2 +
(Password-Based Key Derivation Function)
| 24 | 4 | 16 | Value type
| 28 | 4 | 24 | Value size
| 32 | 24 | | Primary key to unlock the KEKWrappedVolumeKeyStruct +
Contains WrappedKEK
| 56 | 4 | 8 | [yellow-background]*Unknown*
| 60 | 8 | | [yellow-background]*Unknown (empty values)*
| 68 | 4 | 1 | [yellow-background]*Unknown*
| 72 | 72 | | [yellow-background]*Unknown (empty values)*
| 144 | 4 | 1 | [yellow-background]*Unknown*
| 148 | 4 | 3 | [yellow-background]*Unknown*
| 152 | 4 | 10 | [yellow-background]*Unknown*
| 156 | 12 | | [yellow-background]*Unknown*
| 168 | 4 | | [yellow-background]*Unknown*
| 172 | 4 | | Number of iterations for the PBKDF2 +
(Password-Based Key Derivation Function)
| 176 | 4 | 1 | [yellow-background]*Unknown*
| 180 | 4 | 3 | [yellow-background]*Unknown*
| 184 | 4 | 10 | [yellow-background]*Unknown*
| 188 | 96 | | [yellow-background]*Unknown*
|===

=== [[key_encrypted_key_wrapped_volume_key]]Key encrypted key wrapped volume key
The Key encrypted key wrapped volume key (KEKWrappedVolumeKeyStruct) is 256 
bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | 2 | Value type
| 4 | 4 | 24 | Value size
| 8 | 24 | | Volume key +
Contains a <<wrapped_kek,WrappedKEK>>
| 32 | 4 | 8 | [yellow-background]*Unknown*
| 36 | 8 | | [yellow-background]*Unknown (empty values)*
| 44 | 4 | 1 | [yellow-background]*Unknown*
| 48 | 4 | | [yellow-background]*Unknown (empty values)*
| 52 | 4 | 1 | [yellow-background]*Unknown*
| 56 | 4 | 8 | [yellow-background]*Unknown*
| 60 | 8 | | [yellow-background]*Unknown (empty values)*
| 68 | 4 | 1 | [yellow-background]*Unknown*
| 72 | 72 | | [yellow-background]*Unknown (empty values)*
| 144 | 4 | 1 | [yellow-background]*Unknown*
| 148 | 4 | 3 | [yellow-background]*Unknown*
| 152 | 4 | 10 | [yellow-background]*Unknown*
| 156 | 96 | | [yellow-background]*Unknown*
| 252 | 4 | 1 | [yellow-background]*Unknown*
|===

=== [[wrapped_kek]]WrappedKEK
The WrappedKEK is 24 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Initialization vector +
Once unencrypted it should be: +
"\xa6\xa6\xa6\xa6\xa6\xa6\xa6\xa6"
| 8 | 16 | | Key data
|===

== Notes
The metadata can be seen as having a hierarchical structure, where each 
metadata block is composed of:

* a metadata block header
* a metadata block data

If the "volume groups descriptor" from the metadata block header is not empty 
(i.e. is different than 0x00000000), then this metadata block points to some 
sub-blocks (children blocks), which might be or not encrypted depending on the 
type of the parent metadata block or some other information (unsure of this for 
now).

For example, in one test image, the first disklabel metadata appears to have 
4096 sub-blocks. Most of these 4096 are encrypted (with keys from the CS 
header), but some of them (e.g. blocks 60-61) are zero (so when decrypted we 
should expect some crappy data).

Note: I see that the tool only outputs some of these blocks while in 
debug/verbose mode and then goes to decrypt the EncryptedRoot.plist.wipekey 
file. Or am I missing something?

The CoreStorage header provides the pointers to four parent metadata blocks, 
which we call DiskLabel metadata. These parent blocks seem to have type 0x0011. 
The size of these parent blocks is defined in the volume header, in the 
"metadata size" field; this is commonly 4 MiB.

=== Backup of EncryptedRoot.plist.wipekey?
/System/Library/Caches/com.apple.corestorage/EncryptedRoot.plist.wipekey

=== Determining the logical volume size and offset
The "com.apple.corestorage.lv.size" in the plist in metadata block data type 
0x001a contains the logical volume size. 

For a system volume this value should correspond with the extent in the 
metadata block data type 0x0505 which provides the block number of the start of 
the logical volume. ([yellow-background]*is this always the first encrypted 
metadata revision set number 2?*)

For a removable disk

* primary or secondary encrypted metadata + encrypted metadata size?

=== Block type 0x0011
....
checksum                                   : 0x1eef1926 
initial value                              : 0xffffffff 
version                                    : 1 
type                                       : 0x0011 
serial number                              : 0x01120400 
unknown2                                   : 0x00002598 
unknown3                                   : 0x00000000 
number                                     : 0 
unknown5                                   : 0x00000000 
size                                       : 8192 
unknown6                                   : 0x00000000 
unknown7                                   : 0x00000000 

data: 
00000000: 00 00 40 00 03 00 00 00  f9 92 3b bf ff ff ff ff   ..@..... ..;..... 
00000010: 07 57 7e c0 00 04 12 01  00 07 12 01 10 27 01 00   .W~..... .....'.. 
00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
... 
00000050: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000060: 00 00 00 00 00 00 00 00  0c 00 00 00 0d 00 00 00   ........ ........ 
00000070: 40 00 00 00 30 00 01 00  01 00 00 00 01 00 01 00   @...0... ........ 
00000080: 00 08 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000090: 00 00 00 00 00 00 00 00  00 00 00 00 00 20 00 00   ........ ..... .. 
000000a0: 30 20 00 00 79 01 00 00  79 01 00 00 00 00 00 00   0 ..y... y....... 
000000b0: 14 cc c0 01 00 00 00 00  0a 00 00 00 00 00 00 00   ........ ........ 

Block type 0x0011 (2nd)
000000c0: 98 25 00 00 00 00 00 00  0c 00 00 00 00 00 00 00   .%...... ........ 
000000d0: 22 00 00 00 00 00 00 00                            "....... .%...... 

Block type 0x0011 (1st)
000000d0:                          97 25 00 00 00 00 00 00   "....... .%...... 
000000e0: 0c 00 00 00 00 00 00 00  1e 00 00 00 00 00 00 00   ........ ........ 

Block type 0x0011 (4th)
000000f0: 96 25 00 00 00 00 00 00  0c 00 00 00 00 00 00 00   .%...... ........ 
00000100: 1a 00 00 00 00 00 00 00                            ........ .%...... 

Block type 0x0011 (3rd)
00000100:                          95 25 00 00 00 00 00 00   ........ .%...... 
00000110: 0c 00 00 00 00 00 00 00  16 00 00 00 00 00 00 00   ........ ........ 


00000120: 92 25 00 00 00 00 00 00  0b 00 00 00 00 00 00 00   .%...... ........ 
00000130: 17 00 00 00 00 00 00 00  91 25 00 00 00 00 00 00   ........ .%...... 
00000140: 0b 00 00 00 00 00 00 00  13 00 00 00 00 00 00 00   ........ ........ 
00000150: 90 25 00 00 00 00 00 00  0b 00 00 00 00 00 00 00   .%...... ........ 
00000160: 0f 00 00 00 00 00 00 00  8f 25 00 00 00 00 00 00   ........ .%...... 
00000170: 0b 00 00 00 00 00 00 00  0b 00 00 00 00 00 00 00   ........ ........ 
00000180: 8c 25 00 00 00 00 00 00  16 00 00 00 00 00 00 00   .%...... ........ 
00000190: 0c 00 00 00 00 00 00 00  8b 25 00 00 00 00 00 00   ........ .%...... 
000001a0: 16 00 00 00 00 00 00 00  08 00 00 00 00 00 00 00   ........ ........ 

000001b0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
... 
00001fb0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
....

=== Block types 0x0022 and 0x001d
....
checksum                               : 0x51b5a132 
initial value                          : 0xffffffff 
version                                : 1 
block type                             : 0x0022 
unknown1                               : 0x01120700 
unknown2                               : 0x00000002 
unknown3                               : 0x00000004 
unknown4                               : 0x00000004 
unknown5                               : 0x00000000 
block size                             : 8192 
unknown6                               : 0x00000000 
unknown7                               : 0x00000000 

metadata block data: 
00000000: 00 00 00 00 00 00 00 00  92 00 00 00 00 00 00 00   ........ ........ 
00000010: 00 ec 07 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
...
00001210: 00 ec 07 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00001220: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00001230: 69 ec 06 00 00 00 00 00  01 00 00 00 00 00 00 00   i....... ........ 
00001240: 05 00 00 00 00 00 00 00  05 00 00 00 00 00 00 00   ........ ........ 
00001250: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
... 
00001fb0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 

checksum                               : 0x99ea659e 
initial value                          : 0xffffffff 
version                                : 1 
block type                             : 0x001d 
unknown1                               : 0x01120700 
unknown2                               : 0x00000002 
unknown3                               : 0x00000005 
unknown4                               : 0x00000005 
unknown5                               : 0x00000000 
block size                             : 8192 
unknown6                               : 0x00000000 
unknown7                               : 0x00000000 

metadata block data: 
00000000: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000010: 01 00 00 00 00 00 00 00  69 ec 06 00 00 00 00 00   ........ i....... 
00000020: 00 d8 a1 2b 00 00 00 00  00 00 00 00 00 00 00 00   ...+.... ........ 
00000030: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
... 
00001fb0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 


checksum                               : 0x54045a48 
initial value                          : 0xffffffff 
version                                : 1 
block type                             : 0x0022 
unknown1                               : 0x01120700 
unknown2                               : 0x00000002 
unknown3                               : 0x0000000a 
unknown4                               : 0x0000000a 
unknown5                               : 0x00000000 
block size                             : 8192 
unknown6                               : 0x00000000 
unknown7                               : 0x00000000 

metadata block data: 
00000000: 09 00 00 00 00 00 00 00  fd 00 00 00 00 00 00 00   ........ ........ 
00000010: ff c3 07 00 00 00 00 00  01 00 00 00 00 00 00 00   ........ ........ 
00000020: 0b 00 00 00 00 00 00 00  0b 00 00 00 00 00 00 00   ........ ........ 
00000030: 00 ec 07 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000040: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
...

checksum                               : 0xb1ecee27 
initial value                          : 0xffffffff 
version                                : 1 
block type                             : 0x0022 
unknown1                               : 0x01120700 
unknown2                               : 0x00000002 
unknown3                               : 0x00000006 
unknown4                               : 0x00000006 
unknown5                               : 0x00000000 
block size                             : 8192 
unknown6                               : 0x00000000 
unknown7                               : 0x00000000 

metadata block data: 
00000000: 04 00 00 00 00 00 00 00  fd 00 00 00 00 00 00 00   ........ ........ 
00000010: 00 ec 07 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 

...

checksum                               : 0xf2f518f9 
initial value                          : 0xffffffff 
version                                : 1 
block type                             : 0x0022 
unknown1                               : 0x01120700 
unknown2                               : 0x00000002 
unknown3                               : 0x00000008 
unknown4                               : 0x00000008 
unknown5                               : 0x00000000 
block size                             : 8192 
unknown6                               : 0x00000000 
unknown7                               : 0x00000000 

metadata block data: 
00000000: 07 00 00 00 00 00 00 00  fd 00 00 00 00 00 00 00   ........ ........ 
00000010: 00 ec 07 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
...
00001f90: 00 ec 07 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00001fa0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00001fb0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 

...

checksum                               : 0x4577e5ff 
initial value                          : 0xffffffff 
version                                : 1 
block type                             : 0x001d 
unknown1                               : 0x01120700 
unknown2                               : 0x00000002 
unknown3                               : 0x0000000b 
unknown4                               : 0x0000000b 
unknown5                               : 0x00000000 
block size                             : 8192 
unknown6                               : 0x00000000 
unknown7                               : 0x00000000 

metadata block data: 
00000000: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
00000010: 01 00 00 00 00 00 00 00  ff c3 07 00 00 00 00 00   ........ ........ 
00000020: 01 28 00 00 00 00 00 00  00 00 00 00 00 00 00 00   .(...... ........ 
00000030: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
... 
00001fb0: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ........ ........ 
....

=== Removable volume
....
dd if=/dev/zero of=fv2test.raw bs=1024000 count=512

hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount fv2test.raw

Create GPT partition and create HFS+ file-system on it (needs HFS system on osx 10.8)

diskutil cs convert /dev/disk1s1 -passphrase

256 MiB too small to convert a FV2 volume 1 GiB works

Does not create an encryption context? Encrypted extents?

10005000  08 9e ce 5a 21 c4 f1 0b  12 8d 25 27 52 86 66 9e  |...Z!.....%'R.f.|
...
3bffa000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

Reverting volume fills volume at offset 0x5000


Alternative method:
sudo diskutil cs create TESTLVG disk2


dd if=/dev/zero of=fv2test.raw bs=1024 count=$(( 1024 * 1024 )) 
hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount fv2test.raw 
diskutil cs create TESTLVG disk2 
get LVG_UUID from the output of the previous command or “diskutil cs list”

diskutil cs createVolume $LVG_UUID jhfs+ TestLV 100%
diskutil cs createVolume $LVG_UUID jhfs+ TestLV 100% -passphrase
hdiutil detach /dev/disk3
hdiutil detach /dev/disk2

16 MiB too small to create a CS volume, 64 MiB works (to create CS) but not encrypted volume, 1GiB works

diskutil cs decryptVolume $LV_UUID
will decrypt the volume but the data on-disk is still encrypted with the key data in the volume header.
....

=== Core storage
Logical Volume Group

* One or more physical volumes
  * Logical Volume Family
  * Logical Volume

:numbered!:
[appendix]
== References

`[IEEE 1619-2007]`

[cols="1,5",options="header"]
|===
| Title: | The XTS-AES Tweakable Block Cipher (IEEE 1619-2007 )
| Author(s): | IEEE
| Date: | April 18, 2008
| URL: | http://axelkenzo.ru/downloads/1619-2007-NIST-Submission.pdf +
https://bitbucket.org/garethl/xtssharp/src/0e6a81a823e9/docs/1619-2007-NIST-Submission.pdf
|===

`[RFC2898]`
[cols="1,5",options="header"]
|===
| Title: | PKCS #5: Password-Based Cryptography Specification
| Version: | 2.0
| URL: | http://tools.ietf.org/html/rfc2898
|===

`[WIKIPEDIA-PBKDF2]`

[cols="1,5",options="header"]
|===
| Title: | PBKDF2
| URL: | http://en.wikipedia.org/wiki/PBKDF2
|===

[appendix]
== GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc. 
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license 
document, but changing it is not allowed.

=== 0. PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional 
and useful document "free" in the sense of freedom: to assure everyone the 
effective freedom to copy and redistribute it, with or without modifying it, 
either commercially or noncommercially. Secondarily, this License preserves for 
the author and publisher a way to get credit for their work, while not being 
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the 
document must themselves be free in the same sense. It complements the GNU 
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software, 
because free software needs free documentation: a free program should come with 
manuals providing the same freedoms that the software does. But this License is 
not limited to software manuals; it can be used for any textual work, 
regardless of subject matter or whether it is published as a printed book. We 
recommend this License principally for works whose purpose is instruction or 
reference.

=== 1. APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains 
a notice placed by the copyright holder saying it can be distributed under the 
terms of this License. Such a notice grants a world-wide, royalty-free license, 
unlimited in duration, to use that work under the conditions stated herein. The 
"Document", below, refers to any such manual or work. Any member of the public 
is a licensee, and is addressed as "you". You accept the license if you copy, 
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or 
a portion of it, either copied verbatim, or with modifications and/or 
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the 
Document that deals exclusively with the relationship of the publishers or 
authors of the Document to the Document's overall subject (or to related 
matters) and contains nothing that could fall directly within that overall 
subject. (Thus, if the Document is in part a textbook of mathematics, a 
Secondary Section may not explain any mathematics.) The relationship could be a 
matter of historical connection with the subject or with related matters, or of 
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are 
designated, as being those of Invariant Sections, in the notice that says that 
the Document is released under this License. If a section does not fit the 
above definition of Secondary then it is not allowed to be designated as 
Invariant. The Document may contain zero Invariant Sections. If the Document 
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as 
Front-Cover Texts or Back-Cover Texts, in the notice that says that the 
Document is released under this License. A Front-Cover Text may be at most 5 
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented 
in a format whose specification is available to the general public, that is 
suitable for revising the document straightforwardly with generic text editors 
or (for images composed of pixels) generic paint programs or (for drawings) 
some widely available drawing editor, and that is suitable for input to text 
formatters or for automatic translation to a variety of formats suitable for 
input to text formatters. A copy made in an otherwise Transparent file format 
whose markup, or absence of markup, has been arranged to thwart or discourage 
subsequent modification by readers is not Transparent. An image format is not 
Transparent if used for any substantial amount of text. A copy that is not 
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without 
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly 
available DTD, and standard-conforming simple HTML, PostScript or PDF designed 
for human modification. Examples of transparent image formats include PNG, XCF 
and JPG. Opaque formats include proprietary formats that can be read and edited 
only by proprietary word processors, SGML or XML for which the DTD and/or 
processing tools are not generally available, and the machine-generated HTML, 
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such 
following pages as are needed to hold, legibly, the material this License 
requires to appear in the title page. For works in formats which do not have 
any title page as such, "Title Page" means the text near the most prominent 
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the 
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title 
either is precisely XYZ or contains XYZ in parentheses following text that 
translates XYZ in another language. (Here XYZ stands for a specific section 
name mentioned below, such as "Acknowledgements", "Dedications", 
"Endorsements", or "History".) To "Preserve the Title" of such a section when 
you modify the Document means that it remains a section "Entitled XYZ" 
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states 
that this License applies to the Document. These Warranty Disclaimers are 
considered to be included by reference in this License, but only as regards 
disclaiming warranties: any other implication that these Warranty Disclaimers 
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or 
noncommercially, provided that this License, the copyright notices, and the 
license notice saying this License applies to the Document are reproduced in 
all copies, and that you add no other conditions whatsoever to those of this 
License. You may not use technical measures to obstruct or control the reading 
or further copying of the copies you make or distribute. However, you may 
accept compensation in exchange for copies. If you distribute a large enough 
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may 
publicly display copies.

=== 3. COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed 
covers) of the Document, numbering more than 100, and the Document's license 
notice requires Cover Texts, you must enclose the copies in covers that carry, 
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front 
cover, and Back-Cover Texts on the back cover. Both covers must also clearly 
and legibly identify you as the publisher of these copies. The front cover must 
present the full title with all words of the title equally prominent and 
visible. You may add other material on the covers in addition. Copying with 
changes limited to the covers, as long as they preserve the title of the 
Document and satisfy these conditions, can be treated as verbatim copying in 
other respects.

If the required texts for either cover are too voluminous to fit legibly, you 
should put the first ones listed (as many as fit reasonably) on the actual 
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than 
100, you must either include a machine-readable Transparent copy along with 
each Opaque copy, or state in or with each Opaque copy a computer-network 
location from which the general network-using public has access to download 
using public-standard network protocols a complete Transparent copy of the 
Document, free of added material. If you use the latter option, you must take 
reasonably prudent steps, when you begin distribution of Opaque copies in 
quantity, to ensure that this Transparent copy will remain thus accessible at 
the stated location until at least one year after the last time you distribute 
an Opaque copy (directly or through your agents or retailers) of that edition 
to the public.

It is requested, but not required, that you contact the authors of the Document 
well before redistributing any large number of copies, to give them a chance to 
provide you with an updated version of the Document.

=== 4. MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the 
conditions of sections 2 and 3 above, provided that you release the Modified 
Version under precisely this License, with the Modified Version filling the 
role of the Document, thus licensing distribution and modification of the 
Modified Version to whoever possesses a copy of it. In addition, you must do 
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that 
of the Document, and from those of previous versions (which should, if there 
were any, be listed in the History section of the Document). You may use the 
same title as a previous version if the original publisher of that version 
gives permission. 

B. List on the Title Page, as authors, one or more persons or entities 
responsible for authorship of the modifications in the Modified Version, 
together with at least five of the principal authors of the Document (all of 
its principal authors, if it has fewer than five), unless they release you from 
this requirement. 

C. State on the Title page the name of the publisher of the Modified Version, 
as the publisher. 

D. Preserve all the copyright notices of the Document. 

E. Add an appropriate copyright notice for your modifications adjacent to the 
other copyright notices. 

F. Include, immediately after the copyright notices, a license notice giving 
the public permission to use the Modified Version under the terms of this 
License, in the form shown in the Addendum below. 

G. Preserve in that license notice the full lists of Invariant Sections and 
required Cover Texts given in the Document's license notice. 

H. Include an unaltered copy of this License. 

I. Preserve the section Entitled "History", Preserve its Title, and add to it 
an item stating at least the title, year, new authors, and publisher of the 
Modified Version as given on the Title Page. If there is no section Entitled 
"History" in the Document, create one stating the title, year, authors, and 
publisher of the Document as given on its Title Page, then add an item 
describing the Modified Version as stated in the previous sentence. 

J. Preserve the network location, if any, given in the Document for public 
access to a Transparent copy of the Document, and likewise the network 
locations given in the Document for previous versions it was based on. These 
may be placed in the "History" section. You may omit a network location for a 
work that was published at least four years before the Document itself, or if 
the original publisher of the version it refers to gives permission. 

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the 
Title of the section, and preserve in the section all the substance and tone of 
each of the contributor acknowledgements and/or dedications given therein. 

L. Preserve all the Invariant Sections of the Document, unaltered in their text 
and in their titles. Section numbers or the equivalent are not considered part 
of the section titles. 

M. Delete any section Entitled "Endorsements". Such a section may not be 
included in the Modified Version. 

N. Do not retitle any existing section to be Entitled "Endorsements" or to 
conflict in title with any Invariant Section. 

O. Preserve any Warranty Disclaimers. 

If the Modified Version includes new front-matter sections or appendices that 
qualify as Secondary Sections and contain no material copied from the Document, 
you may at your option designate some or all of these sections as invariant. To 
do this, add their titles to the list of Invariant Sections in the Modified 
Version's license notice. These titles must be distinct from any other section 
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but 
endorsements of your Modified Version by various parties—for example, 
statements of peer review or that the text has been approved by an organization 
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage 
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts 
in the Modified Version. Only one passage of Front-Cover Text and one of 
Back-Cover Text may be added by (or through arrangements made by) any one 
entity. If the Document already includes a cover text for the same cover, 
previously added by you or by arrangement made by the same entity you are 
acting on behalf of, you may not add another; but you may replace the old one, 
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give 
permission to use their names for publicity for or to assert or imply 
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS
You may combine the Document with other documents released under this License, 
under the terms defined in section 4 above for modified versions, provided that 
you include in the combination all of the Invariant Sections of all of the 
original documents, unmodified, and list them all as Invariant Sections of your 
combined work in its license notice, and that you preserve all their Warranty 
Disclaimers.

The combined work need only contain one copy of this License, and multiple 
identical Invariant Sections may be replaced with a single copy. If there are 
multiple Invariant Sections with the same name but different contents, make the 
title of each such section unique by adding at the end of it, in parentheses, 
the name of the original author or publisher of that section if known, or else 
a unique number. Make the same adjustment to the section titles in the list of 
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the 
various original documents, forming one section Entitled "History"; likewise 
combine any sections Entitled "Acknowledgements", and any sections Entitled 
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents 
released under this License, and replace the individual copies of this License 
in the various documents with a single copy that is included in the collection, 
provided that you follow the rules of this License for verbatim copying of each 
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it 
individually under this License, provided you insert a copy of this License 
into the extracted document, and follow this License in all other respects 
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and 
independent documents or works, in or on a volume of a storage or distribution 
medium, is called an "aggregate" if the copyright resulting from the 
compilation is not used to limit the legal rights of the compilation's users 
beyond what the individual works permit. When the Document is included in an 
aggregate, this License does not apply to the other works in the aggregate 
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the 
Document, then if the Document is less than one half of the entire aggregate, 
the Document's Cover Texts may be placed on covers that bracket the Document 
within the aggregate, or the electronic equivalent of covers if the Document is 
in electronic form. Otherwise they must appear on printed covers that bracket 
the whole aggregate.

=== 8. TRANSLATION
Translation is considered a kind of modification, so you may distribute 
translations of the Document under the terms of section 4. Replacing Invariant 
Sections with translations requires special permission from their copyright 
holders, but you may include translations of some or all Invariant Sections in 
addition to the original versions of these Invariant Sections. You may include 
a translation of this License, and all the license notices in the Document, and 
any Warranty Disclaimers, provided that you also include the original English 
version of this License and the original versions of those notices and 
disclaimers. In case of a disagreement between the translation and the original 
version of this License or a notice or disclaimer, the original version will 
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or 
"History", the requirement (section 4) to Preserve its Title (section 1) will 
typically require changing the actual title.

=== 9. TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as 
expressly provided under this License. Any attempt otherwise to copy, modify, 
sublicense, or distribute it is void, and will automatically terminate your 
rights under this License.

However, if you cease all violation of this License, then your license from a 
particular copyright holder is reinstated (a) provisionally, unless and until 
the copyright holder explicitly and finally terminates your license, and (b) 
permanently, if the copyright holder fails to notify you of the violation by 
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated 
permanently if the copyright holder notifies you of the violation by some 
reasonable means, this is the first time you have received notice of violation 
of this License (for any work) from that copyright holder, and you cure the 
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses 
of parties who have received copies or rights from you under this License. If 
your rights have been terminated and not permanently reinstated, receipt of a 
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free 
Documentation License from time to time. Such new versions will be similar in 
spirit to the present version, but may differ in detail to address new problems 
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the 
Document specifies that a particular numbered version of this License "or any 
later version" applies to it, you have the option of following the terms and 
conditions either of that specified version or of any later version that has 
been published (not as a draft) by the Free Software Foundation. If the 
Document does not specify a version number of this License, you may choose any 
version ever published (not as a draft) by the Free Software Foundation. If the 
Document specifies that a proxy can decide which future versions of this 
License can be used, that proxy's public statement of acceptance of a version 
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING
"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide 
Web server that publishes copyrightable works and also provides prominent 
facilities for anybody to edit those works. A public wiki that anybody can edit 
is an example of such a server. A "Massive Multiauthor Collaboration" (or 
"MMC") contained in the site means any set of copyrightable works thus 
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license 
published by Creative Commons Corporation, a not-for-profit corporation with a 
principal place of business in San Francisco, California, as well as future 
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as 
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and 
if all works that were first published under this License somewhere other than 
this MMC, and subsequently incorporated in whole or in part into the MMC, (1) 
had no cover texts or invariant sections, and (2) were thus incorporated prior 
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under 
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC 
is eligible for relicensing.

