# Build from source on OpenBSD.
name: build_openbsd
on: [pull_request, push]
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Start VM
      uses: vmactions/openbsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg_add -I autoconf%2.72 automake%1.16 bison curl gettext-tools git gmake libtool python%3.13
    - name: Build
      shell: openbsd {0}
      run: |
        export AUTOCONF_VERSION="2.72"
        export AUTOMAKE_VERSION="1.16"
        export CFLAGS="-I/usr/local/include"
        export LDFLAGS="-L/usr/local/lib"
        export YACC="bison -y"
        if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
        ./synclibs.sh --use-head
        ./autogen.sh
        ./configure --enable-python --with-libfuse
        gmake -j4
    - name: Run tests
      shell: openbsd {0}
      run: |
        export AUTOCONF_VERSION="2.72"
        export AUTOMAKE_VERSION="1.16"
        export CFLAGS="-I/usr/local/include"
        export LDFLAGS="-L/usr/local/lib"
        export YACC="bison -y"
        tests/runtests.sh -j4 VERBOSE=1
