# Build from source on FreeBSD.
name: build_freebsd
on:
  pull_request:
  push:
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - configure_options: ''
    steps:
    - uses: actions/checkout@v6
    - name: Start VM
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        mem: 4096
        prepare: |
          pkg install -y autoconf automake bash byacc curl flex fusefs-libs gettext git libtool openssl pkgconf
    - name: Download test data
      shell: freebsd {0}
      run: |
        if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
    - name: Build from source
      shell: freebsd {0}
      env:
        CC: ${{ matrix.compiler }}
      run: |
        ./synclibs.sh --use-head
        ./autogen.sh
        ./configure ${{ matrix.configure_options }}
        make > /dev/null
    - name: Run tests
      shell: freebsd {0}
      run: |
        tests/runtests.sh CHECK_WITH_STDERR=1
